user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

recruitement:
    resource: "@RecruitementBundle/Resources/config/routing.yml"
    prefix:   /

associations:
    resource: "@AssociationsBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
